import '../theme/index.css'
import Vue from 'vue'
import {
  Button,
  ButtonGroup,
  Input,
  Form,
  FormItem,
  Row,
  Col,
  Message,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  RadioGroup,
  RadioButton,
  Menu,
  Submenu,
  MenuItemGroup,
  MenuItem,
  Breadcrumb,
  BreadcrumbItem,
  Card,
  Table,
  TableColumn,
  Switch,
  Tooltip,
  Pagination,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Avatar,
  PageHeader,
  Divider,
  Drawer,
  Image,
  Calendar,
  Popover,
  Dialog,
  Loading,
  MessageBox,
  Select,
  Option,
  OptionGroup,
  Tag,
  Tabs,
  TabPane,
  InputNumber,
  Radio,
  TimePicker,
  TimeSelect,
  DatePicker,
  Autocomplete
}
  from 'element-ui'

Vue.use(Button)
Vue.use(ButtonGroup)
Vue.use(Input)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Row)
Vue.use(Col)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(RadioGroup)
Vue.use(RadioButton)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Avatar)
Vue.use(PageHeader)
Vue.use(Divider)
Vue.use(Drawer)
Vue.use(Image)
Vue.use(Calendar)
Vue.use(Popover)
Vue.use(Dialog)
Vue.use(Loading)
Vue.use(Select)
Vue.use(Option)
Vue.use(OptionGroup)
Vue.use(Tag)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(InputNumber)
Vue.use(Radio)
Vue.use(TimePicker)
Vue.use(TimeSelect)
Vue.use(DatePicker)
Vue.use(Autocomplete)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
